### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by lucasfersilva** [lguizi/Nike-Boy#1]
Ola meu amigo, me interessei pelo projeto da nike, aceita alguma ajuda?

**Comment by lguizi** [comment]
aceito sim, logo mais vou atualizar aqui com o que já está pronto, a intenção é reduzir ao máximo o tempo da compra dos sneakers

**Comment by lucasfersilva** [comment]
se quiser me contatar por telegram ou wpp me chama la 24999457003, vamo trabalhar nisso ai to sem nada p fazer na quarentena

**Comment by lguizi** [comment]
ok, acabei de concluir mais uma parte do outro que eu estava trabalhando aqui, se quiser da uma olhada la
https://github.com/lguizi/artwalk-bot

**Comment by ThalisGamer** [comment]
olá, eu queria saber sobre como estar o projeto, pois eu necessito demais kkk so tomo L nos drops :/

**Comment by felps3104** [comment]
eae rapaziada, vcs topam criar um discord pra continuar tocando esse projeto?

**Comment by maxbombis** [comment]
Olá, boa noite. Como está o andamento, precisando de alguma ajuda voluntaria?

**Comment by felps3104** [comment]
Opa.
Eu consegui montar ele pro site da Nike.
Mas agora estou tentando estudar alguma coisa de JavaScript e Nodejs pra
conseguir logar com múltiplas contas e enviar múltiplas ordens de compra.

**Comment by Gustavissimo** [comment]
Vocês que já estão na programação, caso necessitem de ajuda, contem comigo!!
Estudo o mercado de sneakers há certo tempo

**Comment by lguizi** [comment]
Olá bom dia,
o projeto está parado por enquanto, estou usando o que tenho aqui somente para uso próprio.
Talvez eu venha distribuir alguma ferramenta para facilitar vocês nos drops futuramente, mas por enquanto não tenho previsão. Obrigado!
