### ISSUE TITLE
Interesse

### ISSUE THREAD

**Issue by Gustavissimo** [lguizi/Nike-Boy#2]
Olá, me interesso no Bot, assim como auxiliar em seus testes, podemos conversar melhor sobre isso?
Tenho algumas informações provavelmente úteis...
Analiso o mercado de sneakers há um bom tempo.

**Comment by lguizi** [comment]
Olá bom dia,
o projeto está parado por enquanto, estou usando o que tenho aqui somente para uso próprio.
Talvez eu venha distribuir alguma ferramenta para facilitar vocês nos drops futuramente, mas por enquanto não tenho previsão. Obrigado!
